# Generated by Django 2.1.4 on 2018-12-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0031_auto_20181218_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
