# Generated by Django 2.1.4 on 2018-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0034_auto_20181218_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_price1',
            field=models.FloatField(default=80),
        ),
    ]
