# Generated by Django 2.1.4 on 2018-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0035_auto_20181218_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
