# Generated by Django 2.1.4 on 2018-12-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0037_shopcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcar',
            name='Goods_id',
        ),
        migrations.RemoveField(
            model_name='shopcar',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ShopCar',
        ),
    ]
