# Generated by Django 2.1.4 on 2018-12-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0039_shopping_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('image_id', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
