# Generated by Django 2.1.4 on 2018-12-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_book_server', '0040_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
